### ISSUE TITLE
Everytime I activate Buddydrive get an admin-ajax.php error for POST

### ISSUE THREAD

**Issue by jeasysehgal** [imath/buddydrive#38]
Hi There.
I have tried deactivating all plugins switching to default 2015 theme with onlybuddypress and buddydrive activated, go to post something in the activity and in the console I see error 500 internal error method post admin-ajax.php js

I am not very technical and don't understand how to fix this.

Please update the plugin to be compatible with the latest wordpress and buddypress please.

**Comment by imath** [comment]
The plugin is compatible with latest WordPress and BuddyPress releases !

I've just tried posting an update into the BuddyPress activity stream and i don't have this error. If you deactivate BuddyDrive, is the error still there or the error only happens when BuddyDrive is activated.

Also are you doing something special because, by default BuddyDrive doesn't load anything into the activity templates ??

**Comment by imath** [comment]
In your wp-config.php could you activate the debug mode and see if an error/notice is appearing ?

```define('WP_DEBUG', true); ```

**Comment by imath** [comment]
Wasn't able to reproduce... Feel free to reopen if you can describe steps to reproduce.
